version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: suitup-postgres
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - app_internal_network
      - proxy-net

  backend:
    image: ghcr.io/cichy28/suit-up/backend:latest
    container_name: suitup-backend
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./backend/uploads:/app/backend/uploads
      - ./backend/_do_importu:/app/_do_importu
    depends_on:
      - postgres
    command: sh -c "npx prisma migrate deploy && node dist/backend/src/index.js"
    networks:
      - app_internal_network # Komunikacja z bazą danych
      - proxy-net # Wystawienie na zewnątrz przez tunel

  frontend: # Poprawna nazwa serwisu, który serwuje frontend
    image: ghcr.io/cichy28/suit-up/frontend:latest
    container_name: suitup-frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - proxy-net # Wystawienie na zewnątrz przez tunel

networks:
  app_internal_network:
    driver: bridge # Sieć jest tutaj ZEWNĘTRZNA, oczekuje, że zostanie stworzona gdzie indziej

volumes:
  postgres_data:
